#! /bin/csh
if ( $#argv <= 0 || $#argv >= 3 ) then
    echo "引数の数が不正です"
    echo "Usage: CCompile [入力ファイル] [出力ファイル] : 指定された.exeのファイルを作成します。"
    echo "       CCompile [入力ファイル] : 入力ファイル.exeのファイルを作成します。"
    echo ""
    echo "Copyright right holders of the [CCompile] is  Takahashi Kazuteru."
    echo ""
    exit
endif

if ( $#argv == 1 ) then
    if(-f $argv[1]:r.exe ) then
        echo "同じ名前の実行ファイルが既に存在します : $argv[1]:r.exe"
        echo -n "上書きしますか？( yes / other ) >> "
        set hantei = $<
        if ( $hantei != "y" && $hantei != "Y" && $hantei != "yes" && $hantei != "Yes"  ) then
            echo "コンパイルを中止します"  
            echo ""
            echo "Copyright right holders of the [CCompile] is  Takahashi Kazuteru."
            echo ""
            exit  
        endif
    endif
    echo "gcc -Wall -o $argv[1]:r.exe $argv[1] -lm" 
    gcc -Wall -o $argv[1]:r.exe $argv[1] -lm
    echo ""
    echo "Copyright right holders of the [CCompile] is  Takahashi Kazuteru."
    echo ""
    exit   
endif

if( ! -f $argv[1] ) then
    echo "指定されたファイルが見つかりませんでした"
    echo ""
    echo "Copyright right holders of the [CCompile] is  Takahashi Kazuteru."
    echo ""
    exit
endif   

if( -f $argv[2] ) then
    echo "同じ名前の実行ファイルが既に存在します : $argv[2]"
    echo -n "上書きしますか？( yes / other ) >> "
    set hantei = $<
    if ( $hantei != "y" && $hantei != "Y" && $hantei != "yes" && $hantei != "Yes"  ) then
        echo "コンパイルを中止します"
        echo ""
        echo "Copyright right holders of the [CCompile] is  Takahashi Kazuteru."
        echo ""
        exit
    endif
endif   

echo "gcc -Wall -o $argv[2] $argv[1] -lm" 
gcc -Wall -o $argv[2] $argv[1] -lm
echo ""
echo "Copyright right holders of the [CCompile] is  Takahashi Kazuteru."
echo ""
