#!/bin/csh
#Macの隠しファイルの表示・非表示を変更するプログラムです。

if( $#argv != 1 )then
    echo "Usage : HiddenFileCommand [true or false]"
    echo ""
    exit
endif

if( $argv[1] == "true" || $argv[1] == "True" || $argv[1] == "TRUE" || $argv[1] == "false" || $argv[1] == "False" || $argv[1] == "FALSE" )then
    defaults write com.apple.finder AppleShowAllFiles -boolean $argv[1]
    killall Finder
else
    echo "Usage : HiddenFileCommand [true or false]"
    echo ""
    exit
endif

echo "Finderを再起動します"
echo ""
